In [3]:
import pandas as pd
df=pd.read_csv("學生月考成績.csv")
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0   NaN  86.0  82.0  89.0
2   s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw   NaN  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0   NaN
5   s1110006  吳雅婷  女         1110006@happy  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
7   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110007@happy.edu.tw  -1.0  -1.0  -1.0  -1.0  -1.0
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0   NaN  88.0  80.0  82.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0   NaN  90.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  -1.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  -1.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0   NaN  95.0  84.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw   NaN  55.0  72.0  52.0  52.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  -1.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

In [3]:
df.head()

         學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0  s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1  s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0   NaN  86.0  82.0  89.0
2  s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3  s1110004  趙人豪  男  1110004@happy.edu.tw   NaN  85.0  80.0  88.0  82.0
4  s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0   NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學號      30 non-null     object
 1   姓名      30 non-null     object
 2   性別      30 non-null     object
 3   電郵      30 non-null     object
 4   國文      28 non-null     float64
 5   英文      28 non-null     float64
 6   數學      29 non-null     float64
 7   歷史      29 non-null     float64
 8   地理      29 non-null     float64
dtypes: float64(5), object(4)
memory usage: 2.2+ KB

In [6]:
df.describe()

              國文         英文         數學         歷史         地理
count  28.000000  28.000000  29.000000  29.000000  29.000000
mean   69.964286  73.678571  76.482759  76.517241  76.896552
std    24.345480  24.331132  21.903393  22.146623  25.866891
min    -1.000000  -1.000000  -1.000000  -1.000000  -1.000000
25%    64.750000  66.000000  63.000000  62.000000  70.000000
50%    76.000000  84.000000  86.000000  82.000000  84.000000
75%    85.500000  87.250000  92.000000  93.000000  93.000000
max    94.000000  97.000000  99.000000  99.000000  99.000000

In [7]:
s = pd.Series([1, 2, 3])
s.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [8]:
s = pd.Series(['a', 'a', 'b', 'c'])
s.describe()

count     4
unique    3
top       a
freq      2
dtype: object

In [10]:
import numpy as np
s = pd.Series([
  np.datetime64("2000-01-01"),
  np.datetime64("2010-01-01"),
  np.datetime64("2010-01-01")
])
s.describe(datetime_is_numeric=True)

count                      3
mean     2006-09-01 08:00:00
min      2000-01-01 00:00:00
25%      2004-12-31 12:00:00
50%      2010-01-01 00:00:00
75%      2010-01-01 00:00:00
max      2010-01-01 00:00:00
dtype: object

In [11]:
condition=df.isnull().any(axis="columns")
df[condition]

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0   NaN  86.0  82.0  89.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw   NaN  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0   NaN
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0   NaN  88.0  80.0  82.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0   NaN  90.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0   NaN  95.0  84.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw   NaN  55.0  72.0  52.0  52.0

In [15]:
df=pd.read_csv("學生月考成績.csv")
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 0 to 29
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學號      23 non-null     object
 1   姓名      23 non-null     object
 2   性別      23 non-null     object
 3   電郵      23 non-null     object
 4   國文      23 non-null     float64
 5   英文      23 non-null     float64
 6   數學      23 non-null     float64
 7   歷史      23 non-null     float64
 8   地理      23 non-null     float64
dtypes: float64(5), object(4)
memory usage: 1.8+ KB

In [16]:
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
2   s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
5   s1110006  吳雅婷  女         1110006@happy  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
7   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110007@happy.edu.tw  -1.0  -1.0  -1.0  -1.0  -1.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  -1.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  -1.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  -1.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

In [7]:
df = pd.read_csv('學生月考成績.csv')
df['國文'] = df['國文'].fillna(df['國文'].mean())
df['英文'] = df['英文'].fillna(df['英文'].mean())
df['數學'] = df['數學'].fillna(df['數學'].mean())
df['歷史'] = df['歷史'].fillna(df['歷史'].mean())
df['地理'] = df['地理'].fillna(df['地理'].mean())
df

,學號,姓名,性別,電郵,國文,英文,數學,歷史,地理
0,s1110001,李彥文,男,1110001@happy.edu.tw,90.000000,85.000000,98.000000,88.000000,96.000000
1,s1110002,吳佳樺,女,1110002@happy.edu.tw,75.000000,73.678571,86.000000,82.000000,89.000000
2,s1110003,劉豪春,男,1110003happy.edu.tw,83.000000,88.000000,74.000000,75.000000,83.000000
3,s1110004,趙人豪,男,1110004@happy.edu.tw,69.964286,85.000000,80.000000,88.000000,82.000000
4,s1110005,杜清芷,女,1110005@happy.edu.tw,51.000000,66.000000,51.000000,77.000000,76.896552
5,s1110006,吳雅婷,女,1110006@happy,94.000000,62.000000,90.000000,62.000000,85.000000
6,s1110007,周常明,男,1110008@happy.edu.tw,74.000000,84.000000,94.000000,82.000000,99.000000
7,s1110007,周常明,男,1110008@happy.edu.tw,74.000000,84.000000,94.000000,82.000000,99.000000
8,s1110009,張呈康,男,1110007@happy.edu.tw,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
9,s1110010,林芳仲,男,1110010@happy.edu.tw,85.000000,73.678571,88.000000,80.000000,82.000000
10,s1110011,林喬羽,男,1110011@happy.edu.tw,45.000000,86.000000,89.000000,97.000000,68.000000
11,s1110012,張家賢,男,1110012@happy.edu.tw,89.000000,71.000000,73.000000,76.517241,90.000000
12,s1110013,許淑芬,女,1110013@happy.edu.tw,47.000000,83.000000,87.000000,71.000000,56.000000
13,s1110014,林美萱,女,1110014@happy.edu.tw,-1.000000,96.000000,88.000000,89.000000,99.000000
14,s1110015,楊惠玟,女,1110015@happy.edu.tw,77.000000,85.000000,93.000000,98.000000,80.000000
15,s1110016,林瓊文,女,1110016@happy.edu.tw,91.000000,88.000000,60.000000,54.000000,46.000000
16,s1110017,連旺美,女,1110017@happy.edu.tw,92.000000,86.000000,83.000000,93.000000,98.000000
17,s1110018,李岳玟,女,1110018@happy.edu.tw,65.000000,65.000000,59.000000,46.000000,93.000000
18,s1110019,李怡璇,女,1110019@happy.edu.tw,68.000000,-1.000000,45.000000,58.000000,91.000000
19,s1110020,陳賢民,男,1110020@happy.edu.tw,90.000000,97.000000,88.000000,98.000000,86.000000
20,s1110021,林昆輝,男,1110021@happy.edu.tw,69.000000,66.000000,76.482759,95.000000,84.000000
21,s1110022,劉峻豪,男,1110022@happy.edu.tw,53.000000,50.000000,51.000000,95.000000,70.000000
22,s1110023,陳信平,男,1110023@happy.edu.tw,70.000000,75.000000,97.000000,89.000000,83.000000
23,s1110024,吳堯嬌,女,1110024@happy.edu.tw,69.964286,55.000000,72.000000,52.000000,52.000000
24,s1110025,呂芳瑜,女,1110025@happy.edu.tw,84.000000,67.000000,53.000000,55.000000,96.000000
25,s1110026,張祐善,男,1110026@happy.edu.tw,87.000000,93.000000,99.000000,97.000000,98.000000
26,s1110027,周志凡,男,1110027@happy.edu.tw,78.000000,89.000000,92.000000,52.000000,-1.000000
27,s1110028,李行財,男,1110028@happy.edu.tw,82.000000,87.000000,79.000000,88.000000,79.000000
28,s1110029,方啟盈,男,1110029@happy.edu.tw,64.000000,88.000000,63.000000,99.000000,63.000000
29,s1110030,何嘉祥,男,1110030@happy.edu.tw,84.000000,84.000000,93.000000,78.000000,85.000000

In [18]:
df.fillna(method="backfill")

,學號,姓名,性別,電郵,國文,英文,數學,歷史,地理
0,s1110001,李彥文,男,1110001@happy.edu.tw,90.000000,85.000000,98.000000,88.000000,96.000000
1,s1110002,吳佳樺,女,1110002@happy.edu.tw,75.000000,73.678571,86.000000,82.000000,89.000000
2,s1110003,劉豪春,男,1110003happy.edu.tw,83.000000,88.000000,74.000000,75.000000,83.000000
3,s1110004,趙人豪,男,1110004@happy.edu.tw,69.964286,85.000000,80.000000,88.000000,82.000000
4,s1110005,杜清芷,女,1110005@happy.edu.tw,51.000000,66.000000,51.000000,77.000000,76.896552
5,s1110006,吳雅婷,女,1110006@happy,94.000000,62.000000,90.000000,62.000000,85.000000
6,s1110007,周常明,男,1110008@happy.edu.tw,74.000000,84.000000,94.000000,82.000000,99.000000
7,s1110007,周常明,男,1110008@happy.edu.tw,74.000000,84.000000,94.000000,82.000000,99.000000
8,s1110009,張呈康,男,1110007@happy.edu.tw,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
9,s1110010,林芳仲,男,1110010@happy.edu.tw,85.000000,73.678571,88.000000,80.000000,82.000000
10,s1110011,林喬羽,男,1110011@happy.edu.tw,45.000000,86.000000,89.000000,97.000000,68.000000
11,s1110012,張家賢,男,1110012@happy.edu.tw,89.000000,71.000000,73.000000,76.517241,90.000000
12,s1110013,許淑芬,女,1110013@happy.edu.tw,47.000000,83.000000,87.000000,71.000000,56.000000
13,s1110014,林美萱,女,1110014@happy.edu.tw,-1.000000,96.000000,88.000000,89.000000,99.000000
14,s1110015,楊惠玟,女,1110015@happy.edu.tw,77.000000,85.000000,93.000000,98.000000,80.000000
15,s1110016,林瓊文,女,1110016@happy.edu.tw,91.000000,88.000000,60.000000,54.000000,46.000000
16,s1110017,連旺美,女,1110017@happy.edu.tw,92.000000,86.000000,83.000000,93.000000,98.000000
17,s1110018,李岳玟,女,1110018@happy.edu.tw,65.000000,65.000000,59.000000,46.000000,93.000000
18,s1110019,李怡璇,女,1110019@happy.edu.tw,68.000000,-1.000000,45.000000,58.000000,91.000000
19,s1110020,陳賢民,男,1110020@happy.edu.tw,90.000000,97.000000,88.000000,98.000000,86.000000
20,s1110021,林昆輝,男,1110021@happy.edu.tw,69.000000,66.000000,76.482759,95.000000,84.000000
21,s1110022,劉峻豪,男,1110022@happy.edu.tw,53.000000,50.000000,51.000000,95.000000,70.000000
22,s1110023,陳信平,男,1110023@happy.edu.tw,70.000000,75.000000,97.000000,89.000000,83.000000
23,s1110024,吳堯嬌,女,1110024@happy.edu.tw,69.964286,55.000000,72.000000,52.000000,52.000000
24,s1110025,呂芳瑜,女,1110025@happy.edu.tw,84.000000,67.000000,53.000000,55.000000,96.000000
25,s1110026,張祐善,男,1110026@happy.edu.tw,87.000000,93.000000,99.000000,97.000000,98.000000
26,s1110027,周志凡,男,1110027@happy.edu.tw,78.000000,89.000000,92.000000,52.000000,-1.000000
27,s1110028,李行財,男,1110028@happy.edu.tw,82.000000,87.000000,79.000000,88.000000,79.000000
28,s1110029,方啟盈,男,1110029@happy.edu.tw,64.000000,88.000000,63.000000,99.000000,63.000000
29,s1110030,何嘉祥,男,1110030@happy.edu.tw,84.000000,84.000000,93.000000,78.000000,85.000000

In [19]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [20]:
df[df.duplicated()]

         學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
7  s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0

In [23]:
df=df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 0 to 29
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學號      29 non-null     object
 1   姓名      29 non-null     object
 2   性別      29 non-null     object
 3   電郵      29 non-null     object
 4   國文      27 non-null     float64
 5   英文      27 non-null     float64
 6   數學      28 non-null     float64
 7   歷史      28 non-null     float64
 8   地理      28 non-null     float64
dtypes: float64(5), object(4)
memory usage: 2.3+ KB

In [25]:

df = pd.read_csv('學生月考成績.csv')
df = df.dropna()
colname = '國文'
Q1 = df[colname].quantile(0.25)
Q3 = df[colname].quantile(0.75)
IQR = Q3 - Q1
upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR
df1 = df[(df[colname]<lower) | (df[colname]>upper)]
print(df1.shape[0])
df1

2

          學號   姓名 性別                    電郵   國文    英文    數學    歷史    地理
8   s1110009  張呈康  男  1110007@happy.edu.tw -1.0  -1.0  -1.0  -1.0  -1.0
13  s1110014  林美萱  女  1110014@happy.edu.tw -1.0  96.0  88.0  89.0  99.0

In [26]:
df = pd.read_csv('學生月考成績.csv')
df = df.dropna()
colname = '英文'
Q1 = df[colname].quantile(0.25)
Q3 = df[colname].quantile(0.75)
IQR = Q3 - Q1
upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR
df1 = df[(df[colname]<lower) | (df[colname]>upper)]
print(df1.shape[0])
df1

2

          學號   姓名 性別                    電郵    國文   英文    數學    歷史    地理
8   s1110009  張呈康  男  1110007@happy.edu.tw  -1.0 -1.0  -1.0  -1.0  -1.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0 -1.0  45.0  58.0  91.0

In [28]:
df = pd.read_csv('學生月考成績.csv')
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0   NaN  86.0  82.0  89.0
2   s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw   NaN  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0   NaN
5   s1110006  吳雅婷  女         1110006@happy  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
7   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110007@happy.edu.tw  -1.0  -1.0  -1.0  -1.0  -1.0
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0   NaN  88.0  80.0  82.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0   NaN  90.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  -1.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  -1.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0   NaN  95.0  84.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw   NaN  55.0  72.0  52.0  52.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  -1.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

#HW

In [32]:
#空值異常值補60
df = pd.read_csv('學生月考成績.csv')
df=df.fillna(60)
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0  60.0  86.0  82.0  89.0
2   s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw  60.0  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0  60.0
5   s1110006  吳雅婷  女         1110006@happy  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
7   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110007@happy.edu.tw  -1.0  -1.0  -1.0  -1.0  -1.0
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0  60.0  88.0  80.0  82.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0  60.0  90.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  -1.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  -1.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0  60.0  95.0  84.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw  60.0  55.0  72.0  52.0  52.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  -1.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

In [99]:
df = pd.read_csv('學生月考成績.csv')
df = df.fillna(60)
df.loc[df['國文']<0, '國文'] = 0  
df.loc[df['英文']<0, '英文'] = 0
df.loc[df['數學']<0, '數學'] = 0
df.loc[df['歷史']<0, '歷史'] = 0
df.loc[df['地理']<0, '地理'] = 0
df = df.drop_duplicates()
df = df.replace(0, 60)
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0  60.0  86.0  82.0  89.0
2   s1110003  劉豪春  男   1110003happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw  60.0  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0  60.0
5   s1110006  吳雅婷  女         1110006@happy  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110008@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110007@happy.edu.tw  60.0  60.0  60.0  60.0  60.0
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0  60.0  88.0  80.0  82.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0  60.0  90.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  60.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  60.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0  60.0  95.0  84.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw  60.0  55.0  72.0  52.0  52.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  60.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

In [104]:
df['電郵'].str

In [114]:
df['電郵'] = df['學號'].str[1:8]+ '@happy.edu.tw'
df

          學號   姓名 性別                    電郵    國文    英文    數學    歷史    地理
0   s1110001  李彥文  男  1110001@happy.edu.tw  90.0  85.0  98.0  88.0  96.0
1   s1110002  吳佳樺  女  1110002@happy.edu.tw  75.0  60.0  86.0  82.0  89.0
2   s1110003  劉豪春  男  1110003@happy.edu.tw  83.0  88.0  74.0  75.0  83.0
3   s1110004  趙人豪  男  1110004@happy.edu.tw  60.0  85.0  80.0  88.0  82.0
4   s1110005  杜清芷  女  1110005@happy.edu.tw  51.0  66.0  51.0  77.0  60.0
5   s1110006  吳雅婷  女  1110006@happy.edu.tw  94.0  62.0  90.0  62.0  85.0
6   s1110007  周常明  男  1110007@happy.edu.tw  74.0  84.0  94.0  82.0  99.0
8   s1110009  張呈康  男  1110009@happy.edu.tw  60.0  60.0  60.0  60.0  60.0
9   s1110010  林芳仲  男  1110010@happy.edu.tw  85.0  60.0  88.0  80.0  82.0
10  s1110011  林喬羽  男  1110011@happy.edu.tw  45.0  86.0  89.0  97.0  68.0
11  s1110012  張家賢  男  1110012@happy.edu.tw  89.0  71.0  73.0  60.0  90.0
12  s1110013  許淑芬  女  1110013@happy.edu.tw  47.0  83.0  87.0  71.0  56.0
13  s1110014  林美萱  女  1110014@happy.edu.tw  60.0  96.0  88.0  89.0  99.0
14  s1110015  楊惠玟  女  1110015@happy.edu.tw  77.0  85.0  93.0  98.0  80.0
15  s1110016  林瓊文  女  1110016@happy.edu.tw  91.0  88.0  60.0  54.0  46.0
16  s1110017  連旺美  女  1110017@happy.edu.tw  92.0  86.0  83.0  93.0  98.0
17  s1110018  李岳玟  女  1110018@happy.edu.tw  65.0  65.0  59.0  46.0  93.0
18  s1110019  李怡璇  女  1110019@happy.edu.tw  68.0  60.0  45.0  58.0  91.0
19  s1110020  陳賢民  男  1110020@happy.edu.tw  90.0  97.0  88.0  98.0  86.0
20  s1110021  林昆輝  男  1110021@happy.edu.tw  69.0  66.0  60.0  95.0  84.0
21  s1110022  劉峻豪  男  1110022@happy.edu.tw  53.0  50.0  51.0  95.0  70.0
22  s1110023  陳信平  男  1110023@happy.edu.tw  70.0  75.0  97.0  89.0  83.0
23  s1110024  吳堯嬌  女  1110024@happy.edu.tw  60.0  55.0  72.0  52.0  52.0
24  s1110025  呂芳瑜  女  1110025@happy.edu.tw  84.0  67.0  53.0  55.0  96.0
25  s1110026  張祐善  男  1110026@happy.edu.tw  87.0  93.0  99.0  97.0  98.0
26  s1110027  周志凡  男  1110027@happy.edu.tw  78.0  89.0  92.0  52.0  60.0
27  s1110028  李行財  男  1110028@happy.edu.tw  82.0  87.0  79.0  88.0  79.0
28  s1110029  方啟盈  男  1110029@happy.edu.tw  64.0  88.0  63.0  99.0  63.0
29  s1110030  何嘉祥  男  1110030@happy.edu.tw  84.0  84.0  93.0  78.0  85.0

In [ ]:
df.to_csv('學生月考成績更正版.csv')